import os

DEFAULT_DOT_SIZE = 1500
DOT_SCALING_AMOUNT = 1000

# COLOR_PALETTE = "Pastel1"
# COLOR_PALETTE = "Set3"
COLOR_PALETTE = "Set2"

CLUSTER_LAYOUT = "circular"
NODE_LAYOUT = "circular"
CLUSTER_K_DIST = 1
NODE_K_DIST = 0.7
